/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.gmf.runtime.notation.validation;

import java.util.Map;

import org.eclipse.emf.common.util.EList;

import org.eclipse.gmf.runtime.notation.Sorting;

/**
 * A sample validator interface for {@link org.eclipse.gmf.runtime.notation.SortingStyle}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SortingStyleValidator {
	boolean validate();

	boolean validateSorting(Sorting value);
	boolean validateSortingKeys(Map value);
	boolean validateSortedObjects(EList value);
}
